M48
; DRILL file {KiCad 9.0.6} date 2025-12-13T20:02:17-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-13T20:02:17-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X207.11Y-85.65
X207.11Y-88.65
T2
X178.85Y-62.03
X183.7Y-62.03
T3
X178.55Y-59.0
X184.0Y-59.0
M30
